# frozen_string_literal: true

# Get the absolute path of the current directory
CURRENT_PATH = File.dirname(__FILE__)

# Import files from the same directory
import File.join(CURRENT_PATH, "helpers.rb")
import File.join(CURRENT_PATH, "configs.rb")
import File.join(CURRENT_PATH, "common_lanes.rb")
import File.join(CURRENT_PATH, "android_lanes.rb")
import File.join(CURRENT_PATH, "ios_lanes.rb")